### ISSUE TITLE
tp

### ISSUE THREAD

**Issue by xCrayl** [xKrayl/PUBG-RageMP#1]
daniel halt deine fresse
``
`//tp kommandzentralle v.88.1 卐
using System;
using GTANetworkAPI;
//
public class teleport : Script
{
    
	
	/* Native tp command
	void START_PLAYER_TELEPORT(Player player, float x, float y, float z, float heading, BOOL p5, BOOL p6, BOOL p7) // AD15F075A4DA0FDE*/

    [Command("tpc", "enter as here: tpc posX Posy Posz  //only spacebar"pos_X=float,pos_Y=float,pos_Z=float )]
    public void tp_coord(Client sender,float pos_X,float pos_Y,float Pos_Z)
    {
      NAPI.Native.SendNativeToPlayer(Client player,0xAD15F075A4DA0FDE,pos_X,pos_Y, Pos_Z);	
}
/*
    //Teleport to specified location
 [Command("tp")]
    public void tp_landmark(Client sender,string landmark)
    {
      NAPI.Native.SendNativeToPlayer(Client player, ulong/Hash longHash, params object[] args);	
	} 
}*///daniel du bistn spastiiiiii xd 卐`

**Comment by Phlenum** [comment]
Ja Daniel, halt mal deine Fresse.


Flachzange.
